services:
  postgres:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432" # Map the container's port 5432 to your local machine
    environment:
      POSTGRES_USER: postgres # Replace with your desired username
      POSTGRES_PASSWORD: password # Replace with your desired password
      POSTGRES_DB: mydatabase # Replace with your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
